{"name": "Successful login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\t(No symbol) [0x003337D3]\n\t(No symbol) [0x002C8B81]\n\t(No symbol) [0x001CB36D]\n\t(No symbol) [0x001FD382]\n\t(No symbol) [0x001FD4BB]\n\t(No symbol) [0x00233302]\n\t(No symbol) [0x0021B464]\n\t(No symbol) [0x00231215]\n\t(No symbol) [0x0021B216]\n\t(No symbol) [0x001F0D97]\n\t(No symbol) [0x001F253D]\n\tGetHandleVerifier [0x005AABF2+2510930]\n\tGetHandleVerifier [0x005D8EC1+2700065]\n\tGetHandleVerifier [0x005DC86C+2714828]\n\tGetHandleVerifier [0x003E3480+645344]\n\t(No symbol) [0x002D0FD2]\n\t(No symbol) [0x002D6C68]\n\t(No symbol) [0x002D6D4B]\n\t(No symbol) [0x002E0D6B]\n\tBaseThreadInitThunk [0x771E00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77D77BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77D77B8E+238]\n\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 52, in step_impl\n    wait.until(EC.visibility_of_element_located((By.XPATH, \"//*[@id='root']/section/section/header/div/div[1]/div/img\")))\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1679955100065, "stop": 1679955102094}, {"name": "When I enter my valid username and password", "status": "passed", "start": 1679955102094, "stop": 1679955103442}, {"name": "And I click on the login button", "status": "passed", "start": 1679955103443, "stop": 1679955103998}, {"name": "Then I should see my personal dashboard", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\t(No symbol) [0x003337D3]\n\t(No symbol) [0x002C8B81]\n\t(No symbol) [0x001CB36D]\n\t(No symbol) [0x001FD382]\n\t(No symbol) [0x001FD4BB]\n\t(No symbol) [0x00233302]\n\t(No symbol) [0x0021B464]\n\t(No symbol) [0x00231215]\n\t(No symbol) [0x0021B216]\n\t(No symbol) [0x001F0D97]\n\t(No symbol) [0x001F253D]\n\tGetHandleVerifier [0x005AABF2+2510930]\n\tGetHandleVerifier [0x005D8EC1+2700065]\n\tGetHandleVerifier [0x005DC86C+2714828]\n\tGetHandleVerifier [0x003E3480+645344]\n\t(No symbol) [0x002D0FD2]\n\t(No symbol) [0x002D6C68]\n\t(No symbol) [0x002D6D4B]\n\t(No symbol) [0x002E0D6B]\n\tBaseThreadInitThunk [0x771E00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77D77BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77D77B8E+238]\n\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 52, in step_impl\n    wait.until(EC.visibility_of_element_located((By.XPATH, \"//*[@id='root']/section/section/header/div/div[1]/div/img\")))\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1679955103999, "stop": 1679955115411}], "start": 1679955100065, "stop": 1679955115412, "uuid": "5d69c4cc-daad-40c7-a9c4-2e64df4fab00", "historyId": "82e6fd88a69b5968ce989053b7ddc5a8", "fullName": "Login: Successful login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}