{"name": "Successful login", "status": "failed", "statusDetails": {"message": "AssertionError: El dashboard no está presente en la página\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 54, in step_impl\n    assert result == \"Existe\", \"El dashboard no está presente en la página\"\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1678812494398, "stop": 1678812496936}, {"name": "When I enter my valid username and password", "status": "passed", "start": 1678812496936, "stop": 1678812498347}, {"name": "And I click on the login button", "status": "passed", "start": 1678812498347, "stop": 1678812498905}, {"name": "Then I should see my personal dashboard", "status": "failed", "statusDetails": {"message": "AssertionError: El dashboard no está presente en la página\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 54, in step_impl\n    assert result == \"Existe\", \"El dashboard no está presente en la página\"\n"}, "start": 1678812498905, "stop": 1678812510939}], "start": 1678812494398, "stop": 1678812510939, "uuid": "e65feeac-1c46-4661-99a4-fb070a8c99ff", "historyId": "82e6fd88a69b5968ce989053b7ddc5a8", "fullName": "Login: Successful login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}