{"name": "Successful login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\t(No symbol) [0x006C37D3]\n\t(No symbol) [0x00658B81]\n\t(No symbol) [0x0055B36D]\n\t(No symbol) [0x0058D382]\n\t(No symbol) [0x0058D4BB]\n\t(No symbol) [0x005C3302]\n\t(No symbol) [0x005AB464]\n\t(No symbol) [0x005C1215]\n\t(No symbol) [0x005AB216]\n\t(No symbol) [0x00580D97]\n\t(No symbol) [0x0058253D]\n\tGetHandleVerifier [0x0093ABF2+2510930]\n\tGetHandleVerifier [0x00968EC1+2700065]\n\tGetHandleVerifier [0x0096C86C+2714828]\n\tGetHandleVerifier [0x00773480+645344]\n\t(No symbol) [0x00660FD2]\n\t(No symbol) [0x00666C68]\n\t(No symbol) [0x00666D4B]\n\t(No symbol) [0x00670D6B]\n\tBaseThreadInitThunk [0x771E00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77D77BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77D77B8E+238]\n\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 51, in step_impl\n    wait.until(EC.visibility_of_element_located((By.XPATH, \"//*[@id='root']/section/section/header/div/div[1]/div/img\")))\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1679679226307, "stop": 1679679229723}, {"name": "When I enter my valid username and password", "status": "passed", "start": 1679679229723, "stop": 1679679231214}, {"name": "And I click on the login button", "status": "passed", "start": 1679679231215, "stop": 1679679231786}, {"name": "Then I should see my personal dashboard", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\t(No symbol) [0x006C37D3]\n\t(No symbol) [0x00658B81]\n\t(No symbol) [0x0055B36D]\n\t(No symbol) [0x0058D382]\n\t(No symbol) [0x0058D4BB]\n\t(No symbol) [0x005C3302]\n\t(No symbol) [0x005AB464]\n\t(No symbol) [0x005C1215]\n\t(No symbol) [0x005AB216]\n\t(No symbol) [0x00580D97]\n\t(No symbol) [0x0058253D]\n\tGetHandleVerifier [0x0093ABF2+2510930]\n\tGetHandleVerifier [0x00968EC1+2700065]\n\tGetHandleVerifier [0x0096C86C+2714828]\n\tGetHandleVerifier [0x00773480+645344]\n\t(No symbol) [0x00660FD2]\n\t(No symbol) [0x00666C68]\n\t(No symbol) [0x00666D4B]\n\t(No symbol) [0x00670D6B]\n\tBaseThreadInitThunk [0x771E00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77D77BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77D77B8E+238]\n\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 51, in step_impl\n    wait.until(EC.visibility_of_element_located((By.XPATH, \"//*[@id='root']/section/section/header/div/div[1]/div/img\")))\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1679679231786, "stop": 1679679244254}], "start": 1679679226306, "stop": 1679679244255, "uuid": "67cf00a2-0926-469f-bbcd-7b4149e24c0e", "historyId": "82e6fd88a69b5968ce989053b7ddc5a8", "fullName": "Login: Successful login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}