{"name": "Failed login with incorrect username and password", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 64, in step_impl\n    ingresar_credenciales(usuario,clave,t)\n  File \"features\\steps\\steps_login.py\", line 17, in ingresar_credenciales\n    f.Texto(\"id\", \"email\", usuario, t)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\Base_page.py\", line 59, in Texto\n    time.sleep(tiempo)\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1679501536182, "stop": 1679501538801}, {"name": "When I enter an invalid username and password", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 64, in step_impl\n    ingresar_credenciales(usuario,clave,t)\n  File \"features\\steps\\steps_login.py\", line 17, in ingresar_credenciales\n    f.Texto(\"id\", \"email\", usuario, t)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\Base_page.py\", line 59, in Texto\n    time.sleep(tiempo)\n"}, "start": 1679501538802, "stop": 1679501539044}, {"name": "And I click on the login button", "status": "skipped", "start": 1679501539045, "stop": 1679501539045}, {"name": "Then I should see an error message \"Please enter a valid email address.\" indicating that the credentials are incorrect", "status": "skipped", "start": 1679501539045, "stop": 1679501539045}], "start": 1679501536179, "stop": 1679501539045, "uuid": "edffdd73-4d14-4a25-bef6-0566f3d5e2fc", "historyId": "cda3c4908154763c4fbd814d69ab08c3", "fullName": "Login: Failed login with incorrect username and password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}