{"name": "Successful login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\t(No symbol) [0x00A037D3]\n\t(No symbol) [0x00998B81]\n\t(No symbol) [0x0089B36D]\n\t(No symbol) [0x008CD382]\n\t(No symbol) [0x008CD4BB]\n\t(No symbol) [0x00903302]\n\t(No symbol) [0x008EB464]\n\t(No symbol) [0x00901215]\n\t(No symbol) [0x008EB216]\n\t(No symbol) [0x008C0D97]\n\t(No symbol) [0x008C253D]\n\tGetHandleVerifier [0x00C7ABF2+2510930]\n\tGetHandleVerifier [0x00CA8EC1+2700065]\n\tGetHandleVerifier [0x00CAC86C+2714828]\n\tGetHandleVerifier [0x00AB3480+645344]\n\t(No symbol) [0x009A0FD2]\n\t(No symbol) [0x009A6C68]\n\t(No symbol) [0x009A6D4B]\n\t(No symbol) [0x009B0D6B]\n\tBaseThreadInitThunk [0x771E00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77D77BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77D77B8E+238]\n\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 57, in step_impl\n    wait.until(EC.visibility_of_element_located((By.XPATH, \"//*[@id='root']/section/section/header/div/div[1]/div/img\")))\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1679501061814, "stop": 1679501064644}, {"name": "When I enter my valid username and password", "status": "passed", "start": 1679501064644, "stop": 1679501065850}, {"name": "And I click on the login button", "status": "passed", "start": 1679501065851, "stop": 1679501066409}, {"name": "Then I should see my personal dashboard", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\t(No symbol) [0x00A037D3]\n\t(No symbol) [0x00998B81]\n\t(No symbol) [0x0089B36D]\n\t(No symbol) [0x008CD382]\n\t(No symbol) [0x008CD4BB]\n\t(No symbol) [0x00903302]\n\t(No symbol) [0x008EB464]\n\t(No symbol) [0x00901215]\n\t(No symbol) [0x008EB216]\n\t(No symbol) [0x008C0D97]\n\t(No symbol) [0x008C253D]\n\tGetHandleVerifier [0x00C7ABF2+2510930]\n\tGetHandleVerifier [0x00CA8EC1+2700065]\n\tGetHandleVerifier [0x00CAC86C+2714828]\n\tGetHandleVerifier [0x00AB3480+645344]\n\t(No symbol) [0x009A0FD2]\n\t(No symbol) [0x009A6C68]\n\t(No symbol) [0x009A6D4B]\n\t(No symbol) [0x009B0D6B]\n\tBaseThreadInitThunk [0x771E00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77D77BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77D77B8E+238]\n\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 57, in step_impl\n    wait.until(EC.visibility_of_element_located((By.XPATH, \"//*[@id='root']/section/section/header/div/div[1]/div/img\")))\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1679501066409, "stop": 1679501077944}], "start": 1679501061814, "stop": 1679501077945, "uuid": "1fbfc408-167b-4121-bc17-fff045398c08", "historyId": "82e6fd88a69b5968ce989053b7ddc5a8", "fullName": "Login: Successful login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}