{"name": "Failed login with incorrect password", "status": "broken", "statusDetails": {"message": "AttributeError: 'Configuration' object has no attribute 'user'\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 49, in step_impl\n    clave = context.config.user\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1678725003672, "stop": 1678725010837}, {"name": "When I enter my valid username and an invalid password", "status": "broken", "statusDetails": {"message": "AttributeError: 'Configuration' object has no attribute 'user'\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 49, in step_impl\n    clave = context.config.user\n"}, "start": 1678725010838, "stop": 1678725010848}, {"name": "And I click on the login button", "status": "broken", "statusDetails": {"message": "\nYou can implement step definitions for undefined steps with these snippets:\n\n@when(u'I click on the login button')\ndef step_impl(context):\n    raise NotImplementedError(u'STEP: When I click on the login button')\n\n"}, "start": 1678725010848, "stop": 1678725010848}, {"name": "Then I should see an error message We can´t seem to find your account indicating that the user account was not found", "status": "broken", "statusDetails": {"message": "\nYou can implement step definitions for undefined steps with these snippets:\n\n@then(u'I should see an error message We can´t seem to find your account indicating that the user account was not found')\ndef step_impl(context):\n    raise NotImplementedError(u'STEP: Then I should see an error message We can´t seem to find your account indicating that the user account was not found')\n\n"}, "start": 1678725010848, "stop": 1678725010848}], "start": 1678725003670, "stop": 1678725010848, "uuid": "f92b41c5-222e-4f86-bc00-fc91c1623c37", "historyId": "86f143c1ecaca072e529a87c9b79271a", "fullName": "Login: Failed login with incorrect password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}