{"name": "Failed login with incorrect password", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button id=\"next\" type=\"submit\" form=\"localAccountForm\">...</button> is not clickable at point (890, 608). Other element would receive the click: <img data-tenant-branding-background=\"true\" src=\"https://aadcdn.msftauthimages.net/dbd5a2dd-qh-zdfszv-cqyaxa3heofkiwbgqw6ngshmcyk-png6a/logintenantbranding/0/illustration?ts=638059372824422599\" alt=\"Background Image\">\n  (Session info: chrome=111.0.5563.110)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x006C37D3]\n\t(No symbol) [0x00658B81]\n\t(No symbol) [0x0055B36D]\n\t(No symbol) [0x00594E3B]\n\t(No symbol) [0x005926DB]\n\t(No symbol) [0x0058FD0B]\n\t(No symbol) [0x0058E4D8]\n\t(No symbol) [0x00583253]\n\t(No symbol) [0x005AB41C]\n\t(No symbol) [0x00582B96]\n\t(No symbol) [0x005AB774]\n\t(No symbol) [0x005C1215]\n\t(No symbol) [0x005AB216]\n\t(No symbol) [0x00580D97]\n\t(No symbol) [0x0058253D]\n\tGetHandleVerifier [0x0093ABF2+2510930]\n\tGetHandleVerifier [0x00968EC1+2700065]\n\tGetHandleVerifier [0x0096C86C+2714828]\n\tGetHandleVerifier [0x00773480+645344]\n\t(No symbol) [0x00660FD2]\n\t(No symbol) [0x00666C68]\n\t(No symbol) [0x00666D4B]\n\t(No symbol) [0x00670D6B]\n\tBaseThreadInitThunk [0x771E00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77D77BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77D77B8E+238]\n\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 68, in step_impl\n    f.Click(\"id\", \"next\", t)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\Base_page.py\", line 79, in Click\n    val.click()\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 93, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 403, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1679677157099, "stop": 1679677164167}, {"name": "When I enter my valid username and an invalid password", "status": "passed", "start": 1679677164167, "stop": 1679677166102}, {"name": "And I click on the login button", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button id=\"next\" type=\"submit\" form=\"localAccountForm\">...</button> is not clickable at point (890, 608). Other element would receive the click: <img data-tenant-branding-background=\"true\" src=\"https://aadcdn.msftauthimages.net/dbd5a2dd-qh-zdfszv-cqyaxa3heofkiwbgqw6ngshmcyk-png6a/logintenantbranding/0/illustration?ts=638059372824422599\" alt=\"Background Image\">\n  (Session info: chrome=111.0.5563.110)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x006C37D3]\n\t(No symbol) [0x00658B81]\n\t(No symbol) [0x0055B36D]\n\t(No symbol) [0x00594E3B]\n\t(No symbol) [0x005926DB]\n\t(No symbol) [0x0058FD0B]\n\t(No symbol) [0x0058E4D8]\n\t(No symbol) [0x00583253]\n\t(No symbol) [0x005AB41C]\n\t(No symbol) [0x00582B96]\n\t(No symbol) [0x005AB774]\n\t(No symbol) [0x005C1215]\n\t(No symbol) [0x005AB216]\n\t(No symbol) [0x00580D97]\n\t(No symbol) [0x0058253D]\n\tGetHandleVerifier [0x0093ABF2+2510930]\n\tGetHandleVerifier [0x00968EC1+2700065]\n\tGetHandleVerifier [0x0096C86C+2714828]\n\tGetHandleVerifier [0x00773480+645344]\n\t(No symbol) [0x00660FD2]\n\t(No symbol) [0x00666C68]\n\t(No symbol) [0x00666D4B]\n\t(No symbol) [0x00670D6B]\n\tBaseThreadInitThunk [0x771E00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77D77BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77D77B8E+238]\n\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 68, in step_impl\n    f.Click(\"id\", \"next\", t)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\Base_page.py\", line 79, in Click\n    val.click()\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 93, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 403, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1679677166102, "stop": 1679677167376}, {"name": "Then I should see an error message Your password is incorrect indicating that the your password is incorrect", "status": "skipped", "start": 1679677167378, "stop": 1679677167378}], "start": 1679677157097, "stop": 1679677167378, "uuid": "25d74a3c-c356-4029-b06b-5215db87bc2c", "historyId": "86f143c1ecaca072e529a87c9b79271a", "fullName": "Login: Failed login with incorrect password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}